### ISSUE TITLE
Panic: runtime error && signal SIGSEGV on startup

### ISSUE THREAD

**Issue by mohafarman** [normen/whatscli#100]
This happens when I try to run the program. 
```
whatscli
```

Full error message:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                            
signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x55bb18616d5f
goroutine 40 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x0?)
github.com/Rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7f
github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001c8a50, 0x0)
github.com/normen/whatscli/messages/session_manager.go:234 +0x1d3
github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001c8a50)
github.com/normen/whatscli/messages/session_manager.go:71 +0x4e
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
github.com/normen/whatscli/messages/session_manager.go:65 +0x6b
```

My specs are:
Lenovo Thinkpad T480 
Linux manjaro 6.1.41-1-MANJARO
Terminal: tmux && urxvt (Error occurs in both terminals)

**Comment by caltuntas** [comment]
The same error on MacOS.
