### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x55d59114753a]

### ISSUE THREAD

**Issue by formula-spectre** [normen/whatscli#107]
Distro: gentoo linux, musl libc
when trying to launch whatscli I get this error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x55d59114753a]

goroutine 40 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x1?)
        /var/tmp/portage/net-misc/whatscli-1.0.11/work/go-mod/github.com/!rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7a
github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0002684d0, 0x0)
        /var/tmp/portage/net-misc/whatscli-1.0.11/work/whatscli-1.0.11/messages/session_manager.go:234 +0x1cd
github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0002684d0)
        /var/tmp/portage/net-misc/whatscli-1.0.11/work/whatscli-1.0.11/messages/session_manager.go:71 +0x45
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager in goroutine 1
        /var/tmp/portage/net-misc/whatscli-1.0.11/work/whatscli-1.0.11/messages/session_manager.go:65 +0x65
```
go version go1.21.4 linux/amd64

**Comment by normen** [comment]
please check the pinned issues
