### ISSUE TITLE
Ctrl+C or Ctrl+V doesn't work and results in error 

### ISSUE THREAD

**Issue by Masacaai** [normen/whatscli#32]
When pressing the above two key combinations, whatscli exits and gives this error message:

```
panic: runtime error: slice bounds out of range [1:0] [recovered]
	panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0001961c0)
	github.com/rivo/tview@v0.0.0-20201118063654-f007e9ad3893/application.go:243 +0x87
panic(0x5563b1e1fba0, 0xc0009a1580)
	runtime/panic.go:969 +0x1b9
github.com/zyedidia/clipboard.getCopyCommand(...)
	github.com/zyedidia/clipboard@v1.0.3/clipboard_unix.go:154
github.com/zyedidia/clipboard.writeAll(0xc0000a9f00, 0x1b, 0x5563b1a2eca2, 0x9, 0x5563b15d2ee8, 0xc000250410)
	github.com/zyedidia/clipboard@v1.0.3/clipboard_unix.go:177 +0x330
github.com/zyedidia/clipboard.WriteAll(...)
	github.com/zyedidia/clipboard@v1.0.3/clipboard.go:21
main.handleCopyUser(0xc00026aae0, 0xc00022b320)
	command-line-arguments/main.go:209 +0x165
gitlab.com/tslocum/cbind.(*Configuration).Capture(0xc00025c090, 0xc00026aae0, 0x0)
	gitlab.com/tslocum/cbind@v0.1.4/configuration.go:111 +0x178
github.com/rivo/tview.(*Application).Run(0xc0001961c0, 0x0, 0x0)
	github.com/rivo/tview@v0.0.0-20201118063654-f007e9ad3893/application.go:314 +0x765
main.main()
	command-line-arguments/main.go:129 +0x1465
```

I'm running the AUR version

**Comment by normen** [comment]
I guess the `zyedidia/clipboard` library doesn't find an appropriate place to put the data. Is xclip working on that machine?

**Comment by Masacaai** [comment]
Do you mean xclipboard?

**Comment by normen** [comment]
I mean the xclip command. https://github.com/astrand/xclip

**Comment by Masacaai** [comment]
I'm sorry, I probably should have done more research before blindly asking about xclipboard. I've tried a few xclip commands and they all seem to be working.

**Comment by aboimpinto** [comment]
Sorry to re-ask this question.
I can use xclip on my Ubuntu, meaning that I can copy something (github web address for example) and in my console when I make: 
```
$ xclip -o 
```
Works well. The question is: How do I paste the same link into WhatsCli??

best regards
Paulo Aboim Pinto

**Comment by normen** [comment]
> Works well. The question is: How do I paste the same link into WhatsCli??

Depends on your terminal. The same way you'd paste something into the command line in general.

**Comment by pendragons-code** [comment]
if you insist on using keybinds, it might work for you (depending on your terminal) ctrl shift c and ctrl shift v
