### ISSUE TITLE
Exception raises when I authenticate with QR-Code

### ISSUE THREAD

**Issue by sblendorio** [normen/whatscli#62]
That's what happens after authenticating:

``` goroutine 40 [running]:
github.com/Rhymen/go-whatsapp.newInfoFromReq(0xc000590000)
/home/sblendorio/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:63 +0x951
github.com/Rhymen/go-whatsapp.(*Conn).Login(0xc00009c000, 0x0)
/home/sblendorio/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:268 +0xd36
 github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001d2f20, 0xc00009c000)
/home/sblendorio/github/whatscli/messages/session_manager.go:234 +0x1e8
   github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001d2f20)
/home/sblendorio/github/whatscli/messages/session_manager.go:71 +0x4e
 created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
/home/sblendorio/github/whatscli/messages/session_manager.go:65 +0x70
```
![image](https://user-images.githubusercontent.com/2118813/151704780-37439217-f6c8-4367-beb6-4fb31b96748f.png)

**Comment by normen** [comment]
Looks like you can't login. The error happens in the go-whatsapp library and can't be caught by whatscli. Maybe they have some similar issues in the bug tracker?
