### ISSUE TITLE
doesn't connect anymore

### ISSUE THREAD

**Issue by kurokirasama** [normen/whatscli#72]
Hello,

I'm having issues connecting. I got this screen for a while:

![whatcli2](https://user-images.githubusercontent.com/5784951/163237649-efcace21-37d5-488d-8b86-6d520d7c0554.png)

Then it changes to this, and it remains  there forever:

![whatcli3](https://user-images.githubusercontent.com/5784951/163237709-fdff2fce-eb28-4059-85cb-e743a7cac135.png)

Also, 2 out of 5 times I run the app I got this screen:

![whatcli](https://user-images.githubusercontent.com/5784951/163237769-31913d57-eb48-4981-9195-5356d8e601c0.png)

Regards,

**Comment by Saliba-san** [comment]
same here!

**Comment by johnwuelk** [comment]
same here, fails on different devices.

**Comment by bbbart** [comment]
yes, that's happening here as well

**Comment by normen** [comment]
Yeah, I guess its time to finish up the [whatsmeow version](https://github.com/normen/whatscli/tree/whatsmeow), I didn't (and probably still won't for some time) find much time to complete that though.

**Comment by sozoalvin** [comment]
does anybody have a clue on where to start debugging? i can help to take a look

**Comment by normen** [comment]
Check out the whatsmeow branch, it should work logging in and retrieving messages. The main remaining thing is storing all needed info of a message (ID?) in the local DB so one can later recreate message objects in a form the whatsmeow library understands (e.g. to retrieve additional info like images, to quote etc.).

**Comment by kurokirasama** [comment]
@normen whatsmeow branch gives me this error when building with `go build`:
```
build github.com/normen/whatscli: cannot load embed: malformed module path "embed": missing dot in first path element
```

**Comment by normen** [comment]
Just use the makefile, something seems to be off there, I don't get this issue. Maybe run a `make get` before.

**Comment by kurokirasama** [comment]
like this?
```
make get Makefile
```
I got the same error, maybe I'm missing some go dependencies...
```
go get
build github.com/normen/whatscli: cannot load embed: malformed module path "embed": missing dot in first path element
make: *** [Makefile:16: get] Error 1
```

**Comment by normen** [comment]
Try pulling again, I pushed my local changes, its all WIP mind you!

**Comment by normen** [comment]
`make get` would be the command but the added `Makefile` doesn't really change anything I guess. No idea whats going wrong there for you.

**Comment by kurokirasama** [comment]
@normen it was a version problem. I had installed 1.13, it was necessary 1.18

**Comment by TheSashmo** [comment]
Is this issue closed or still open?  I can't use the application either, I get the same message as the post lists, 1.11 is the latest release, but I see comments for 1.13 and 1.18.

**Comment by normen** [comment]
> Is this issue closed or still open? I can't use the application either, I get the same message as the post lists, 1.11 is the latest release, but I see comments for 1.13 and 1.18.

In my browser its still open. kurokirasama is talking about the golang version for compiling the WIP branch.

**Comment by b3h3m0th** [comment]
Right, so what you are saying is one should use the whatsmeow branch and the releases aren't broken?

**Comment by normen** [comment]
Seems to depend on the region and settings if its still working. The whatsmeow branch needs to be finished, not debugged.

**Comment by ZobairQ** [comment]
im having the same problem

**Comment by pendragons-code** [comment]
I'm still having this issue

**Comment by icrescenti** [comment]
No solution it seems

**Comment by pendragons-code** [comment]
Indeex

**Comment by pendragons-code** [comment]
I had an older install of whatscli and a ubuntu PC, even that did not work, this means it is a change on whatsapp's end that denies our connection. I doubt we can go anywhere from here unless we can see what this one thing is. I might look at similar projects and see how we can employ some of the methodologies used in said other projects. Despite all that I repeat my point that we might not go anywhere from here.

**Comment by normen** [comment]
Again, the solution is the new whatsmeow library for which a branch of whatscli exists but isn't finished.

**Comment by pendragons-code** [comment]
Thanks, I'll check it out.

**Comment by pendragons-code** [comment]
Yes, I'm still interested.

**Comment by slarrain** [comment]
Hopefully the whatsmeow branch picks up some pace. WhatsApp, unfortunately, is incredibly important to so many millions of people that it deserves a proper CLI/TUI client.

**Comment by normen** [comment]
I'm still swamped in other code and projects. But it's in the back of my mind.

Having looked at the whatsmeow library a bit more, by now I think boiling down the whole codebase to a simple whatsmeow frontend without any abstractions is probably the better way to go.

**Comment by slarrain** [comment]
Thanks @normen . I'd wish this project was done on Python, so I could help you out and you wouldn't have to be the sole developer of this project. Unfortunately, No **GO** for me.

By the way, if you want us to try different branches and versions, just ping us. Good luck with whatsmeow!

**Comment by martin-braun** [comment]
@normen If my understanding is correct, the `whatsmeow` branch is working, but crippled. I respect that there are times where you cannot work on this, this is FOSS and anybody can pickup your work at anytime. However, I think it would be useful to have rather a limited experience than no experience, so how about making an update on Homebrew nonetheless?

**Comment by normen** [comment]
Actually the current version does work for some accounts in some countries, including mine.

**Comment by martin-braun** [comment]
@normen That's interesting. I have a similar issue as OP without even getting to the point of registering the client. It throws an error right after start with the version that I installed using `brew install whatscli`: 

![2023-02-16 3 43 53 PM](https://user-images.githubusercontent.com/24259245/219396873-8130d1fc-cfaa-4d9a-8409-e1ba0eaaf662.gif)

So, the error is `panic: runtime error: invalid memory address or nil pointer dereference`, but the stacktrace is different: 

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x142903f]
goroutine 40 [running]: github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x0?)           github.com/Rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7f
github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001eaa50, 0x0)                                         github.com/normen/whatscli/messages/session_manager.go:234 +0x1d3
github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001eaa50)                                 github.com/normen/whatscli/messages/session_manager.go:71 +0x4e
created by 
github.com/normen/whatscli/messages.(*SessionManager).StartManager                         github.com/normen/whatscli/messages/session_manager.go:65 +0x6b
```

Maybe it was wrong to close #89?

**Comment by normen** [comment]
> Maybe it was wrong to close #89?

No, thats exactly the error everybody else is getting too.

**Comment by ezimir** [comment]
I'm getting same error on PopOS 22.04.

Either compiling from source (git clone, make), or using executables from release assets (out of curiosity, I've tried each 0.X.0 release all the way back to 0.5.0, same error).

Is there anything I can help to help debug this? I've got no experience with go, but I'd very much like a working whatsapp client in terminal.

```
λ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

```
λ go version
go version go1.20.2 linux/amd64
```

**Comment by normen** [comment]
Again: The crash is in the go-whatsapp library, so any changes in code would be in that library - if it was still maintained. 

Currently whatsmeow is the only go library known to work with the new whatsapp multiclient system and using it means a complete rewrite of this software except for the UI part.

**Comment by tripplilley** [comment]
@normen: if you accept https://github.com/normen/homebrew-tap/pull/1, users can help out with the testing (both of the [whatsmeow branch](https://github.com/normen/whatscli/tree/whatsmeow) and of the main branch whenever you start merging back).

In the meantime, anyone who wishes to try out the [whatsmeow branch](https://github.com/normen/whatscli/tree/whatsmeow) can do so immediately by switching over to [my fork of the tap](https://github.com/tripplilley/homebrew-whatscli) and installing from there:

```shellsession
$ brew remove whatscli
$ brew untap normen/tap
$ brew tap tripplilley/whatscli
$ brew install --HEAD whatscli-whatsmeow
$ whatsmeow
```
I have successfully installed and tested basic device linking and message sending on my MBP.

```shellsession
$ uname -a
Darwin gina-inviere.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64 i386 Darwin
````

**Comment by radhesh1** [comment]
Go build shows no module found for crypto/ed25519
And i don't know how to fix that

**Comment by normen** [comment]
The whatsmeow branch is not ready for testing or using at all, its meant for development.

**Comment by 99702** [comment]
`whatsmeow` branch did work. I just need to clone ,, build and run binary.
`git clone -b whatsmeow git@github.com:normen/whatscli.git`
`cd whatscli && go build main.go`
`./whatscli`

**Comment by TheSashmo** [comment]
I can confirm this works, BUT it shows offline status, and any messages that I type go to whatsapp, but I can not see them in the chat.  I can see them on my phone, but no other updates come to the application.  So it's still broken.

**Comment by 99702** [comment]
yes , messages are being sent but it can not see them both messeges i sent and new messages.

**Comment by klownie** [comment]
i can confirm Whatsmew branch works but it does not show a qr code

**Comment by normen** [comment]
Wow I guess I should delete the whatsmeow branch..

**Comment by 99702** [comment]
Rather trying it, nchat (https://github.com/d99kris/nchat) works best for me , for both whatsapp and telegram. It is  two way communication with whatsapp and include alot of more features .

**Comment by tripplilley** [comment]
> Wow I guess I should delete the whatsmeow branch..

Perhaps instead, you could just archive the whole repo? That way it will be obvious that you're not actively maintaining it, and you won't be bothered by issue messages, but the original code and the initial whatsmeow work will stay available to anyone who wants to pick it up in the future?

**Comment by normen** [comment]
> Rather trying it, nchat (https://github.com/d99kris/nchat) works best for me , for both whatsapp and telegram. It is two way communication with whatsapp and include alot of more features .

Nice, I should link that in the README

> Perhaps instead, you could just archive the whole repo? That way it will be obvious that you're not actively maintaining it, and you won't be bothered by issue messages, but the original code and the initial whatsmeow work will stay available to anyone who wants to pick it up in the future?

Nice thought but even with explicit promises to look at the branch nobody did anything - its always possible for anyone to pick up the work. And again, it still works as is for me, so you will either have to wait until I get around to it or be bold enough to make a fork or PR. 🤷‍♂️

**Comment by cdkw2** [comment]
Still the same error

**Comment by radhesh1** [comment]
> > Rather trying it, nchat (https://github.com/d99kris/nchat) works best for me , for both whatsapp and telegram. It is two way communication with whatsapp and include alot of more features .
> 
> Nice, I should link that in the README
> 
> > Perhaps instead, you could just archive the whole repo? That way it will be obvious that you're not actively maintaining it, and you won't be bothered by issue messages, but the original code and the initial whatsmeow work will stay available to anyone who wants to pick it up in the future?
> 
> Nice thought but even with explicit promises to look at the branch nobody did anything - its always possible for anyone to pick up the work. And again, it still works as is for me, so you will either have to wait until I get around to it or be bold enough to make a fork or PR. 🤷‍♂️
> 
> 

See this for future reference

**Comment by radhesh1** [comment]
> Nice thought but even with explicit promises to look at the branch nobody did anything - its always possible for anyone to pick up the work. And again, it still works as is for me, so you will either have to wait until I get around to it or be bold enough to make a fork or PR.

Hi would you put your code as a different branch on this repo?

**Comment by pookdeveloper** [comment]
same error
