### ISSUE TITLE
Segmentation Violation

### ISSUE THREAD

**Issue by Yanik39** [normen/whatscli#82]
Hello,

I am getting the error below as soon as i run the app with latest version on Ubuntu 22.04.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f2e1f]

goroutine 27 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x0)
	/Users/normenhansen/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7f
github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001b51e0, 0x0)
	/Users/normenhansen/Dev/GoCode/whatscli/messages/session_manager.go:234 +0x1e8
github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001b51e0)
	/Users/normenhansen/Dev/GoCode/whatscli/messages/session_manager.go:71 +0x4e
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
	/Users/normenhansen/Dev/GoCode/whatscli/messages/session_manager.go:65 +0x70
```

**Comment by pablo-penovi** [comment]
Exact same issue here, Ubuntu 22.04, kernel 5.15.0-50-generic

**Comment by Yanik39** [comment]
Its go-whatsapp issue and its not under develeopment.
Alternative is [https://github.com/tulir/whatsmeow](url)
But its a lot of work i guess.

**Comment by maxbarroso** [comment]
Exact same issue here, Slackware, kernel 5.15.0-50-generic

**Comment by normen** [comment]
See #72
