### ISSUE TITLE
fedora37: crash on startup

### ISSUE THREAD

**Issue by yuvalif** [normen/whatscli#88]
build from source (`go build`) on fedora37 with: `go version go1.19.4 linux/amd64`
when running `./whatscli` i get:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x831aff]

goroutine 28 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x0?)
  /home/ylifshit/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7f
github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001b4bb0, 0x0)
  /home/ylifshit/projects/whatscli/messages/session_manager.go:234 +0x1d3
github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001b4bb0)
  /home/ylifshit/projects/whatscli/messages/session_manager.go:71 +0x4e
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
  /home/ylifshit/projects/whatscli/messages/session_manager.go:65 +0x6b
```

**Comment by ozanyetkin** [comment]
I am also facing the same issue on archlinux ```6.1.6-arch1-1``` using ```go version go1.19.5 linux/amd64```

**Comment by ju2ez** [comment]
same

**Comment by Recognizer83** [comment]
same issue here as well

**Comment by ArchTonIO** [comment]
Same issue, has anybody found solutions ?

**Comment by coderunner86** [comment]
Same issue

**Comment by normen** [comment]
See #51 and #72
