### ISSUE TITLE
Segfault on launch with v1.0.11

### ISSUE THREAD

**Issue by rubenhorn** [normen/whatscli#94]
Error also occurs when building locally…
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x81ea3f]

goroutine 28 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x0?)
        /[...]/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7f
github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001ab600, 0x0)
        /[...]/whatscli/messages/session_manager.go:234 +0x1d3
github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001ab600)
        /[...]/whatscli/messages/session_manager.go:71 +0x4e
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
        /[...]/whatscli/messages/session_manager.go:65 +0x6b
```

with Go version…
`go version go1.18.3 linux/amd64`

**Comment by normen** [comment]
See pinned issues.
